version: '3.8'

services:

  db:
    image: mysql:5.7.22
    environment: 
      MYSQL_DATABASE: apimastery
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    build: ./devops/docker
    image: apimastery:0.1
    links:
      - db:db
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/var/www/app